const targetWords = [
    a a a â
    e é è ê
    "conta",
    "atrio",
    "tocar",
    "verbo",
    "pardo",
    "lindo",
    "trupe",
    "aurea",
    "fenda",
    "coito",
    "livre",
    "dessa",
    "sabia",
    "alçar",
    "viria",
    "opaco",
    "navio",
    "fraco",
    "retem",
    "afora",
    "ficha",
    "jirau",
    "etico",
    "astro",
    "faixa",
    "parca",
    "elite",
    "festa",
    "supra",
    "oxala",
    "lidar",
    "glosa",
    "autor",
    "mente",
    "verba",
    "tinha",
    "firme",
    "cioso",
    "fatos",
    "magia",
    "grata",
    "fatal",
    "bater",
    "calda",
    "reses",
    "manhã",
    "pique",
    "cousa",
    "junco",
    "privê",
    "deixa",
    "irmão",
    "salve",
    "pagão",
    "molho",
    "macio",
    "douto",
    "abriu",
    "atual",
    "light",
    "bicho",
    "supor",
    "torso",
    "posto",
    "turvo",
    "asilo",
    "igneo",
    "sexta",
    "orfão",
    "extra",
    "judeu",
    "vezes",
    "sarça",
    "curso",
    "caber",
    "rouca",
    "locus",
    "besta",
    "longe",
    "pisar",
    "porta",
    "drops",
    "desta",
    "radio",
    "cânon",
    "abuso",
    "ruina",
    "zelar",
    "video",
    "combo",
    "vosso",
    "bioma",
    "ereto",
    "paira",
    "finda",
    "culpa",
    "vinha",
    "menos",
    "agudo",
    "baixo",
    "feudo",
    "facto",
    "bônus",
    "tetra",
    "advir",
    "urgia",
    "estio",
    "cutis",
    "surja",
    "traço",
    "meigo",
    "nosso",
    "sitio",
    "super",
    "gosto",
    "autos",
    "calão",
    "tento",
    "facho",
    "suave",
    "rumor",
    "amena",
    "pilar",
    "cocho",
    "museu",
    "turma",
    "clean",
    "lasso",
    "chama",
    "ações",
    "geral",
    "acola",
    "louça",
    "optar",
    "pifia",
    "podio",
    "lapis",
    "local",
    "medir",
    "boato",
    "mosto",
    "hobby",
    "julia",
    "rubro",
    "crime",
    "penta",
    "pacto",
    "letal",
    "folga",
    "ponha",
    "refem",
    "drama",
    "brabo",
    "poema",
    "cacho",
    "pareo",
    "cover",
    "aroma",
    "vigia",
    "movel",
    "mesma",
    "hoste",
    "feroz",
    "aluno",
    "vetar",
    "pasmo",
    "fazia",
    "peito",
    "açude",
    "rival",
    "monte",
    "golpe",
    "metiê",
    "finjo",
    "avida",
    "troça",
    "axila",
    "coral",
    "ecoar",
    "teste",
    "forum",
    "chato",
    "lição",
    "riste",
    "daqui",
    "piada",
    "plebe",
    "lesse",
    "forem",
    "monge",
    "artur",
    "clima",
    "poeta",
    "sucia",
    "carta",
    "verde",
    "cetro",
    "ebano",
    "passa",
    "escol",
    "swing",
    "tacha",
    "macro",
    "ateia",
    "falha",
    "venha",
    "briga",
    "calmo",
    "sarau",
    "roupa",
    "conto",
    "viram",
    "broxa",
    "busca",
    "cargo",
    "farta",
    "fruto",
    "tarde",
    "idoso",
    "perco",
    "legua",
    "atimo",
    "plaga",
    "plumo",
    "aviso",
    "tribo",
    "berro",
    "chefe",
    "vento",
    "virar",
    "grama",
    "civil",
    "corso",
    "arado",
    "surto",
    "assar",
    "seixo",
    "estro",
    "bruta",
    "saldo",
    "traje",
    "catre",
    "ornar",
    "recem",
    "nuvem",
    "beijo",
    "pedra",
    "deste",
    "troca",
    "fosso",
    "manga",
    "manga",
    "giria",
    "unica",
    "trato",
    "impia",
    "casar",
    "depor",
    "vedar",
    "deram",
    "porte",
    "arfar",
    "tição",
    "uteis",
    "bença",
    "magna",
    "irado",
    "âmbar",
    "grota",
    "canso",
    "amiga",
    "cifra",
    "amado",
    "silvo",
    "tutor",
    "sosia",
    "bazar",
    "gabar",
    "pasma",
    "vazão",
    "tiver",
    "rural",
    "itens",
    "bruto",
    "laudo",
    "renda",
    "regio",
    "pavor",
    "perto",
    "jejum",
    "segar",
    "bucho",
    "midia",
    "tchau",
    "nesse",
    "inter",
    "troco",
    "minar",
    "feita",
    "odiar",
    "vagar",
    "molde",
    "pinho",
    "viado",
    "orgão",
    "clero",
    "fossa",
    "vadio",
    "areia",
    "lesto",
    "sotão",
    "meche",
    "pomar",
    "aviar",
    "negar",
    "cenho",
    "canto",
    "lesão",
    "mamãe",
    "cinto",
    "largo",
    "rocha",
    "paiol",
    "ileso",
    "visto",
    "horto",
    "bolsa",
    "proto",
    "ruido",
    "pugna",
    "inves",
    "marca",
    "podar",
    "densa",
    "guria",
    "stand",
    "close",
    "morfo",
    "amada",
    "urdir",
    "bunda",
    "ufano",
    "vista",
    "jogar",
    "xucro",
    "vasta",
    "dubia",
    "mocho",
    "civel",
    "frota",
    "penso",
    "chula",
    "bulir",
    "umido",
    "cheia",
    "piche",
    "culta",
    "linha",
    "ubere",
    "peita",
    "esgar",
    "varoa",
    "resto",
    "canil",
    "apear",
    "misto",
    "manto",
    "fundo",
    "demão",
    "natal",
    "monta",
    "agape",
    "narco",
    "fazes",
    "tenha",
    "findo",
    "barão",
    "campa",
    "gemer",
    "nessa",
    "santo",
    "cerca",
    "jazer",
    "chaga",
    "volta",
    "simio",
    "album",
    "preço",
    "velha",
    "mover",
    "retro",
    "polis",
    "ardis",
    "cosmo",
    "logos",
    "labia",
    "letra",
    "verão",
    "venho",
    "folia",
    "seiva",
    "banto",
    "ferpa",
    "punha",
    "matar",
    "alamo",
    "troço",
    "sabor",
    "nesta",
    "porca",
    "etapa",
    "audio",
    "ceita",
    "barro",
    "calça",
    "trago",
    "rente",
    "sigla",
    "coroa",
    "axial",
    "louro",
    "salva",
    "final",
    "firma",
    "redor",
    "arroz",
    "limpo",
    "bolso",
    "torna",
    "tumba",
    "coevo",
    "miope",
    "solta",
    "enjoo",
    "queda",
    "lutar",
    "lousa",
    "baixa",
    "farol",
    "ousar",
    "fugiu",
    "folha",
    "mimar",
    "neste",
    "dança",
    "corar",
    "zumbi",
    "sinta",
    "veloz",
    "burra",
    "nacar",
    "obtem",
    "longo",
    "reler",
    "cacto",
    "macho",
    "fatuo",
    "salmo",
    "penca",
    "forro",
    "vazia",
    "vario",
    "justa",
    "calor",
    "farto",
    "quite",
    "bedel",
    "mania",
    "todas",
    "sugar",
    "lucro",
    "gueto",
    "chave",
    "puido",
    "repor",
    "staff",
    "calvo",
    "ultra",
    "logia",
    "sexto",
    "merda",
    "subir",
    "custo",
    "refil",
    "passe",
    "urgir",
    "viger",
    "sadio",
    "mimos",
    "harem",
    "versa",
    "valer",
    "hifen",
    "lento",
    "usual",
    "socio",
    "redea",
    "cardo",
    "mouro",
    "ardua"
]

const dictionary = [
    "sagaz",
    "âmago",
    "negro",
    "êxito",
    "mexer",
    "termo",
    "senso",
    "nobre",
    "algoz",
    "afeto",
    "plena",
    "etica",
    "mutua",
    "tênue",
    "sutil",
    "vigor",
    "aquem",
    "fazer",
    "porem",
    "audaz",
    "sanar",
    "seção",
    "assim",
    "inato",
    "cerne",
    "ideia",
    "fosse",
    "desde",
    "poder",
    "moral",
    "torpe",
    "muito",
    "honra",
    "justo",
    "futil",
    "gozar",
    "anexo",
    "razão",
    "etnia",
    "quiça",
    "sobre",
    "icone",
    "sonho",
    "tange",
    "egide",
    "lapso",
    "mutuo",
    "expor",
    "haver",
    "amigo",
    "habil",
    "casal",
    "tempo",
    "porra",
    "seara",
    "pesar",
    "avido",
    "então",
    "posse",
    "dengo",
    "boçal",
    "genro",
    "coser",
    "ardil",
    "corja",
    "causa",
    "prole",
    "paria",
    "dizer",
    "detem",
    "tenaz",
    "dever",
    "digno",
    "saber",
    "obice",
    "crivo",
    "graça",
    "apice",
    "ânsia",
    "ânimo",
    "brado",
    "ceder",
    "orgia",
    "comum",
    "gleba",
    "sendo",
    "temor",
    "assaz",
    "culto",
    "atroz",
    "mundo",
    "pauta",
    "censo",
    "fugaz",
    "ainda",
    "cozer",
    "denso",
    "valha",
    "nenem",
    "vicio",
    "forte",
    "estar",
    "vulgo",
    "reves",
    "pudor",
    "regra",
    "dogma",
    "louco",
    "criar",
    "banal",
    "impor",
    "round",
    "tenro",
    "saude",
    "pifio",
    "jeito",
    "desse",
    "ordem",
    "atras",
    "apraz",
    "pedir",
    "mercê",
    "clava",
    "reaça",
    "usura",
    "viril",
    "prosa",
    "juizo",
    "servo",
    "feliz",
    "sabio",
    "ontem",
    "manso",
    "coisa",
    "homem",
    "presa",
    "xibiu",
    "falar",
    "forma",
    "cunho",
    "devir",
    "fluir",
    "afago",
    "meiga",
    "ebrio",
    "platô",
    "mesmo",
    "serio",
    "vendo",
    "guisa",
    "limbo",
    "magoa",
    "visar",
    "pleno",
    "temer",
    "heroi",
    "acaso",
    "cisma",
    "puder",
    "bruma",
    "valor",
    "lugar",
    "êxodo",
    "afins",
    "obvio",
    "gerar",
    "posso",
    "impio",
    "obter",
    "certo",
    "crise",
    "matiz",
    "praxe",
    "senil",
    "havia",
    "vênia",
    "fluxo",
    "enfim",
    "todos",
    "ritmo",
    "tedio",
    "alibi",
    "abrir",
    "união",
    "tomar",
    "garbo",
    "valia",
    "reter",
    "pulha",
    "parvo",
    "visão",
    "falso",
    "facil",
    "vital",
    "grato",
    "favor",
    "bravo",
    "vivaz",
    "prumo",
    "laico",
    "parco",
    "gênio",
    "olhar",
    "ameno",
    "burro",
    "possa",
    "reles",
    "legal",
    "levar",
    "tecer",
    "obito",
    "casta",
    "tesão",
    "prime",
    "selar",
    "anelo",
    "fator",
    "ranço",
    "morte",
    "noção",
    "rogar",
    "citar",
    "façam",
    "farsa",
    "adiar",
    "sabia",
    "achar",
    "cabal",
    "coeso",
    "cisão",
    "epico",
    "noite",
    "nicho",
    "falta",
    "fardo",
    "ouvir",
    "força",
    "ativo",
    "viver",
    "sinto",
    "imune",
    "gente",
    "brega",
    "exato",
    "haste",
    "amplo",
    "passo",
    "lavra",
    "sonso",
    "sulco",
    "dubio",
    "cesta",
    "tendo",
    "leigo",
    "sesta",
    "unico",
    "revel",
    "labor",
    "gesto",
    "deter",
    "vemos",
    "calma",
    "arduo",
    "vadia",
    "humor",
    "atuar",
    "feixe",
    "rever",
    "ciume",
    "linda",
    "otica",
    "pobre",
    "tende",
    "igual",
    "outro",
    "ponto",
    "carma",
    "toada",
    "hiato",
    "velho",
    "sonsa",
    "debil",
    "ideal",
    "claro",
    "vacuo",
    "ajuda",
    "ambos",
    "terno",
    "remir",
    "cauda",
    "varão",
    "fusão",
    "probo",
    "senão",
    "leito",
    "fonte",
    "marco",
    "jovem",
    "advem",
    "doido",
    "horda",
    "inata",
    "capaz",
    "xeque",
    "tenra",
    "relva",
    "terra",
    "algum",
    "ficar",
    "velar",
    "caçar",
    "serie",
    "apoio",
    "farão",
    "anuir",
    "lider",
    "vimos",
    "vazio",
    "rigor",
    "verso",
    "tanto",
    "dorso",
    "coçar",
    "entre",
    "botar",
    "frase",
    "massa",
    "pouco",
    "signo",
    "cruel",
    "sente",
    "prece",
    "moção",
    "coesa",
    "virus",
    "ambas",
    "morar",
    "peste",
    "fauna",
    "casto",
    "raiva",
    "covil",
    "minha",
    "feito",
    "preso",
    "credo",
    "faina",
    "ciclo",
    "furor",
    "lazer",
    "torço",
    "impar",
    "corno",
    "papel",
    "docil",
    "flora",
    "vetor",
    "maior",
    "brisa",
    "chata",
    "arido",
    "aceso",
    "trama",
    "beata",
    "houve",
    "pegar",
    "vulto",
    "blase",
    "manha",
    "adeus",
    "breve",
    "liame",
    "setor",
    "banzo",
    "nossa",
    "vasto",
    "birra",
    "senda",
    "salvo",
    "seita",
    "ardor",
    "livro",
    "morro",
    "peixe",
    "meses",
    "visse",
    "pecha",
    "atomo",
    "prado",
    "antro",
    "reger",
    "chuva",
    "comer",
    "prono",
    "plano",
    "sorte",
    "segue",
    "avaro",
    "saiba",
    "ocaso",
    "rezar",
    "foder",
    "pajem",
    "nunca",
    "alias",
    "carro",
    "saida",
    "otimo",
    "aureo",
    "anciã",
    "junto",
    "acima",
    "mudar",
    "chulo",
    "seria",
    "serão",
    "sinal",
    "opção",
    "fitar",
    "jazia",
    "fruir",
    "treta",
    "parar",
    "fugir",
    "puxar",
    "nação",
    "bando",
    "andar",
    "motim",
    "prazo",
    "grupo",
    "gerir",
    "tosco",
    "leite",
    "norma",
    "lenda",
    "alude",
    "brava",
    "epoca",
    "sinha",
    "rapaz",
    "tenso",
    "parte",
    "exame",
    "campo",
    "avião",
    "idolo",
    "psico",
    "arcar",
    "reino",
    "tirar",
    "venal",
    "soldo",
    "malta",
    "praga",
    "quota",
    "vilão",
    "agora",
    "anais",
    "sumir",
    "corpo",
    "aonde",
    "virão",
    "indio",
    "logro",
    "preto",
    "risco",
    "traga",
    "antes",
    "pompa",
    "fixar",
    "voraz",
    "praia",
    "exijo",
    "cheio",
    "quase",
    "filho",
    "certa",
    "texto",
    "nodoa",
    "oasis",
    "turba",
    "copia",
    "solto",
    "turva",
    "alado",
    "apego",
    "caixa",
    "prova",
    "estão",
    "messe",
    "grave",
    "acesa",
    "doido",
    "parva",
    "nivel",
    "perda",
    "ligar",
    "verve",
    "apelo"
]

const WORD_LENGTH = 5
const FLIP_ANIMATION_DURATION = 500
const DANCE_ANIMATION_DURATION = 500
const keyboard = document.querySelector("[data-keyboard]")
const alertContainer = document.querySelector("[data-alert-container]")
const guessGrid = document.querySelector("[data-guess-grid]")
const offsetFromDate = new Date(2022, 0, 1)
const msOffset = Date.now() - offsetFromDate
const dayOffset = msOffset / 1000 / 60 / 60 / 24
const targetWord = targetWords[Math.floor(dayOffset)]

startInteraction()

function startInteraction() {
  document.addEventListener("click", handleMouseClick)
  document.addEventListener("keydown", handleKeyPress)
}

function stopInteraction() {
  document.removeEventListener("click", handleMouseClick)
  document.removeEventListener("keydown", handleKeyPress)
}

function handleMouseClick(e) {
  if (e.target.matches("[data-key]")) {
    pressKey(e.target.dataset.key)
    return
  }

  if (e.target.matches("[data-enter]")) {
    submitGuess()
    return
  }

  if (e.target.matches("[data-delete]")) {
    deleteKey()
    return
  }
}

function handleKeyPress(e) {
  if (e.key === "Enter") {
    submitGuess()
    return
  }

  if (e.key === "Backspace" || e.key === "Delete") {
    deleteKey()
    return
  }

  if (e.key.match(/^[a-z]$/)) {
    pressKey(e.key)
    return
  }
}

function pressKey(key) {
  const activeTiles = getActiveTiles()
  if (activeTiles.length >= WORD_LENGTH) return
  const nextTile = guessGrid.querySelector(":not([data-letter])")
  nextTile.dataset.letter = key.toLowerCase()
  nextTile.textContent = key
  nextTile.dataset.state = "active"
}

function deleteKey() {
  const activeTiles = getActiveTiles()
  const lastTile = activeTiles[activeTiles.length - 1]
  if (lastTile == null) return
  lastTile.textContent = ""
  delete lastTile.dataset.state
  delete lastTile.dataset.letter
}

function submitGuess() {
  const activeTiles = [...getActiveTiles()]
  if (activeTiles.length !== WORD_LENGTH) {
    showAlert("Not enough letters")
    shakeTiles(activeTiles)
    return
  }

  const guess = activeTiles.reduce((word, tile) => {
    return word + tile.dataset.letter
  }, "")

  if (!dictionary.includes(guess)) {
    showAlert("Not in word list")
    shakeTiles(activeTiles)
    return
  }

  stopInteraction()
  activeTiles.forEach((...params) => flipTile(...params, guess))
}

function flipTile(tile, index, array, guess) {
  const letter = tile.dataset.letter
  const key = keyboard.querySelector(`[data-key="${letter}"i]`)
  setTimeout(() => {
    tile.classList.add("flip")
  }, (index * FLIP_ANIMATION_DURATION) / 2)

  tile.addEventListener(
    "transitionend",
    () => {
      tile.classList.remove("flip")
      if (targetWord[index] === letter) {
        tile.dataset.state = "correct"
        key.classList.add("correct")
      } else if (targetWord.includes(letter)) {
        tile.dataset.state = "wrong-location"
        key.classList.add("wrong-location")
      } else {
        tile.dataset.state = "wrong"
        key.classList.add("wrong")
      }

      if (index === array.length - 1) {
        tile.addEventListener(
          "transitionend",
          () => {
            startInteraction()
            checkWinLose(guess, array)
          },
          { once: true }
        )
      }
    },
    { once: true }
  )
}

function getActiveTiles() {
  return guessGrid.querySelectorAll('[data-state="active"]')
}

function showAlert(message, duration = 1000) {
  const alert = document.createElement("div")
  alert.textContent = message
  alert.classList.add("alert")
  alertContainer.prepend(alert)
  if (duration == null) return

  setTimeout(() => {
    alert.classList.add("hide")
    alert.addEventListener("transitionend", () => {
      alert.remove()
    })
  }, duration)
}

function shakeTiles(tiles) {
  tiles.forEach(tile => {
    tile.classList.add("shake")
    tile.addEventListener(
      "animationend",
      () => {
        tile.classList.remove("shake")
      },
      { once: true }
    )
  })
}

function checkWinLose(guess, tiles) {
  if (guess === targetWord) {
    showAlert("You Win", 5000)
    danceTiles(tiles)
    stopInteraction()
    return
  }

  const remainingTiles = guessGrid.querySelectorAll(":not([data-letter])")
  if (remainingTiles.length === 0) {
    showAlert(targetWord.toUpperCase(), null)
    stopInteraction()
  }
}

function danceTiles(tiles) {
  tiles.forEach((tile, index) => {
    setTimeout(() => {
      tile.classList.add("dance")
      tile.addEventListener(
        "animationend",
        () => {
          tile.classList.remove("dance")
        },
        { once: true }
      )
    }, (index * DANCE_ANIMATION_DURATION) / 5)
  })
}